---
deployment:
  tasks:
    - export COMPOSER_ALLOW_SUPERUSER=1
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
    - npm ci --only=production
    - npm run build
    - mkdir -p storage/logs
    - mkdir -p storage/framework/cache
    - mkdir -p storage/framework/sessions
    - mkdir -p storage/framework/views
    - mkdir -p bootstrap/cache
    - mkdir -p database/backups
    - chmod 755 storage
    - chmod 755 storage/logs
    - chmod 755 storage/framework
    - chmod 755 storage/framework/cache
    - chmod 755 storage/framework/sessions
    - chmod 755 storage/framework/views
    - chmod 755 bootstrap/cache
    - chmod +x database-sync.sh
    - chmod +x deploy.sh
    - chmod +x backup.sh
    - php artisan storage:link
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan view:clear
    - php artisan route:clear
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - echo "Deployment completed successfully" >> storage/logs/deployment.log